version: '3'
services:
  mysql:
    #image: mysql:8.2
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatnio
      MYSQL_USER: chatnio
      MYSQL_PASSWORD: chatnio123456!
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    # expose:
    #   - "3306"
    volumes:
        - ./db:/var/lib/mysql
    networks:
      - chatnio-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    # expose:
    #   - "6379"
    volumes:
      - ./redis:/data
    networks:
      - chatnio-network

  # chatnio:
  #     image: programzmh/chatnio
  #     container_name: chatnio
  #     restart: always
  #     ports:
  #         - "8001:8094"
  #     depends_on:
  #         - mysql
  #         - redis
  #     links:
  #         - mysql
  #         - redis
  #     ulimits:
  #       nofile:
  #         soft: 65535
  #         hard: 65535
  #     environment:
  #         MYSQL_HOST: mysql
  #         MYSQL_USER: chatnio
  #         MYSQL_PASSWORD: chatnio123456!
  #         MYSQL_DB: chatnio
  #         REDIS_HOST: redis
  #         REDIS_PORT: 6379
  #         REDIS_PASSWORD: ""
  #         REDIS_DB: 0
  #         SERVE_STATIC: "false"
  #     volumes:
  #       - ./config:/config
  #       - ./logs:/logs
  #       - ./storage:/storage
  #     networks:
  #       - chatnio-network

networks:
  chatnio-network:
    driver: bridge
